version: "3.8" 

services:
  db:
    image: postgres:16 
    restart: always 
    environment: 
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME} 
    ports:
      - "5433:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 

  api:
    build: . 
    ports:
      - "3000:3000" 
    environment: 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db 
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on: 
      - db
    volumes:
      - .:/app 
    command: ["node", "server.js"] 

volumes:
  db_data: